name:                lambda-chess
version:             0.1.0.0
github:              "githubuser/lambda-chess"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lambda-chess#readme>

dependencies:
- base >= 4.7 && < 5
- chessIO
- lens
- zippers
- rio
- random >= 1.2
- mwc-random
- constraints
- conduit
- ansi-terminal
- fei-base >= 2 && < 3
- fei-nn >= 2 && < 3

library:
  source-dirs: src
  default-extensions:
    NoImplicitPrelude

executables:
  lambda-chess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chess
    - formatting
    - perfect-vector-shuffle
    - binary
    - fei-nn >= 2 && < 3
    - store
    default-extensions:
      NoImplicitPrelude

tests:
  lambda-chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-chess
